### PR TITLE
Fix #373. Fix #358

### LINKED ISSUE #358: Pressing ESC should abort the prompts
When I trigger a mapping and realize I triggered the wrong refactoring my reaction is pressing ESC. But when I do that each refactoring displays a different error or weird behavior.

### LINKED ISSUE #373: Export function to file error
Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:
RPC[Error] code_name = InternalError, message = "Request textDocument/foldingRange failed with message: The document should be opened for foldingRanges', file: /Users/mac/reactProject/wenjuan-fe/src/demo.ts" fn fn.

image

### PR DESCRIPTION
**Pull request by TheLeoP**
This PR fixes #373 (a small change, as described on the issue), uses `Pipeline`  to stop the execution whenever an error occurs (showing the error message via `vim.notify`. Should I add some kind of option to override this?) fixing #358 (if a user doesn't enter a variable name o a file name, the pipeline is stopped and an error message is showed via `vim.notify`) and cleans/refactors some code.

For example, the issue solved by #355 was related to an old workaround on `lsp_utils.lua` (using the same `start` and `end` for an lsp_range used to cause problems. The issue is solved now, so the workaround is no longer needed). As a consecuense of this change, it's possible to differentitate between lsp_ranges where text is going to be inserted and where text is going to be replaced.

### CODE REVIEW

**Comment by pranavrao145** [comment]
Hi @TheLeoP. Thanks for the PR - I will take a look ASAP and merge if it's good to go!

File: lua/refactoring/tests/refactor_spec.lua [hunk 1]
```diff
@@ -51,6 +51,8 @@ local function for_each_file(cb)
 end
 
 local function test_empty_input()
+    -- TODO (TheLeoP): does this make sense?
```
Comment (pranavrao145) [inline lua/refactoring/tests/refactor_spec.lua:54]: I don't think so - could you elaborate as to what was the intention here?

File: lua/refactoring/tasks/apply_text_edits.lua [hunk 2]
```diff
@@ -18,21 +11,17 @@ local function refactor_apply_text_edits(refactor)
     local edits = {}
 
     for _, edit in pairs(refactor.text_edits) do
-        local bufnr = edit.bufnr or refactor.buffers[1]
+        local bufnr = refactor.buffers[1]
```
Comment (pranavrao145) [inline lua/refactoring/tasks/apply_text_edits.lua:14]: I believe this will mess with the "Extract Function to File" functionality (i.e. it will put the function into the same file rather than the new file). While testing this I also found various other errors with the "Extract Function to File" functionality due to small changes in recent commits that I didn't catch before, but I will make a  new PR to address these.

File: lua/refactoring/utils.lua [hunk 3]
```diff
@@ -194,11 +217,12 @@ end
 ---@param node TSNode
 function M.region_above_node(node)
     local scope_region = Region:from_node(node)
-    local lsp_range = scope_region:to_lsp_range()
+    -- TODO (TheLeoP): should I create a special case for this?
```
Comment (pranavrao145) [inline lua/refactoring/utils.lua:220]: Yeah I think it's best just to figure out whether to call replace or insert. Best not to mess with behaviour of util functions unless we need to.

File: lua/refactoring/tasks/apply_text_edits.lua [hunk 4]
```diff
@@ -18,21 +11,17 @@ local function refactor_apply_text_edits(refactor)
...
-            table.insert(edits[bufnr], edit)
-            add_change(Region:from_lsp_range(edit.range, bufnr), edit.newText)
-        else
-            local newText = get_text(edit)
-            table.insert(edits[bufnr], edit.region:to_lsp_text_edit(newText))
-            add_change(edit.region, newText)
-        end
+        table.insert(edits[bufnr], edit)
+        add_change(
+            -- TODO (TheLeoP): Probably this is wrong and I should evaluate whether to insert or replace x2
```
Comment (pranavrao145) [inline lua/refactoring/tasks/apply_text_edits.lua:21]: Yep I agree, best to check just to make sure.

**Review by pranavrao145 — CHANGES_REQUESTED** [review]
@TheLeoP overall looks good, just a couple of minor changes - you already caught most of them with the comments about insert/replace checks. Once these are fixed I can merge - thanks again for your contribution!

File: lua/refactoring/tests/refactor_spec.lua (hunk 1 above)
Comment (TheLeoP) [reply lua/refactoring/tests/refactor_spec.lua:54]: This particular test checks if an error message is the correct one by calling the refactoring function with `pcall`. Since in this PR in using  `vim.notify` to show this errors, in order for  `pcall` to be able to intercept them I overwrote `vim.notify` with `error` for this particular test.

File: lua/refactoring/tasks/apply_text_edits.lua (hunk 2 above)
Comment (TheLeoP) [reply lua/refactoring/tasks/apply_text_edits.lua:14]: You are right. I will fix this.

**Comment by TheLeoP** [comment]
I'm not sure how code revision works on github. I made some changes on my local machine and commited them. While doing them, I also encountered some weird behaviour with extract to file, so I just copied all the changes on #380, but some errors where still there. In particular, when extracting a function which should receive local variables as arguments to a file, it didn't worked. It turned out that `Region:contains` was using the current bufnr as default (the newly created buffer), so it always returned false. I think that error wasn't caused by me in a past commit, but I'm not 100% sure. Nonetheless, I have fixed it.

File: lua/refactoring/tests/refactor_spec.lua (hunk 1 above)
Comment (pranavrao145) [reply lua/refactoring/tests/refactor_spec.lua:54]: Sounds good, I think that makes sense in that case; tests can't pass without it either.

**Review by pranavrao145 — APPROVED** [review]
Thanks for the changes! This looks good to me - I think "Extract Function to File" tests will take a bit more work so we can address it in another PR; I will open a ticket for the same.
